[theme]
primaryColor                = "#2b5af8"
backgroundColor             = "#f8faff"
secondaryBackgroundColor    = "#eef1fc"
textColor                   = "#0d1433"
font                        = "sans serif"

[server]
headless = true
